# Generated by Django 6.0.6 on 2026-07-10 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='site_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='phone_link',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='phone_number',
        ),
    ]
