# Generated by Django 6.0.6 on 2026-07-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_site_name_sitesettings_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
