# Generated by Django 6.0.6 on 2026-07-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sitesettings_address_alter_sitesettings_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Martin Boxabl', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='name',
            field=models.CharField(default='Martin Noe Costas', max_length=100),
        ),
    ]
