# Generated by Django 6.0.6 on 2026-07-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_site_name_alter_sitesettings_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_name',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ceo',
            field=models.CharField(default='Martin Noe Costas', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='name',
            field=models.CharField(default='Martin Boxabl', max_length=100),
        ),
    ]
