# Generated by Django 6.0.6 on 2026-07-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_sitesettings_site_name_sitesettings_ceo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='wa_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
