# Generated by Django 6.0.6 on 2026-10-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_wa_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='canonical_domain',
            field=models.URLField(blank=True, default='https://martinboxabl.com'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_tag_manager_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
    ]
