# Generated by Django 6.0.6 on 2026-07-22 08:21

import django.db.models.deletion
import taggit.managers
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='blogindexpage',
            options={'verbose_name': 'Blog Index Page', 'verbose_name_plural': 'Blog Index Pages'},
        ),
        migrations.AlterModelOptions(
            name='blogpostpage',
            options={'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='author',
            field=models.CharField(default='Martin Boxabl', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short summary displayed on blog cards.', max_length=300),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='intro',
            field=models.TextField(blank=True, help_text='Short introduction displayed above blog posts.'),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.fields.RichTextField(),
        ),
        migrations.AddField(
            model_name='blogpostpage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory'),
        ),
    ]
