# Generated by Django 6.0.6 on 2026-07-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcategory_alter_blogindexpage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogindexpage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='blogpostpage',
            options={},
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='excerpt',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
