# Generated by Django 6.0.6 on 2026-07-10 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('badge', models.CharField(blank=True, max_length=100)),
                ('series', models.CharField(blank=True, max_length=100)),
                ('short_description', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='homes/')),
                ('spec_sheet', models.FileField(blank=True, null=True, upload_to='spec-sheets/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_per_sqft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('square_feet', models.PositiveIntegerField()),
                ('bedrooms', models.PositiveSmallIntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=3)),
                ('stories', models.PositiveSmallIntegerField(default=1)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homes', to='shop.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HomeGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homes/gallery/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='shop.home')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='shop.home')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
