# Generated by Django 6.0.6 on 2026-07-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='badge',
        ),
        migrations.AddField(
            model_name='home',
            name='best_seller',
            field=models.BooleanField(default=True),
        ),
    ]
