# Generated by Django 6.0.6 on 2026-07-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_home_badge_home_best_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='best_seller',
        ),
        migrations.AddField(
            model_name='home',
            name='badge',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
