# Generated by Django 6.0.6 on 2026-07-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_hometype_alter_home_category_home_home_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometype',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
