# Generated by Django 6.0.6 on 2026-07-21 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_hometype_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hometype',
            options={'ordering': ('name',), 'verbose_name': 'Home Type', 'verbose_name_plural': 'Home Types'},
        ),
    ]
