# Generated by Django 6.0.6 on 2026-07-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_hometype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hometype',
            options={'ordering': ['name'], 'verbose_name': 'Home Type', 'verbose_name_plural': 'Home Types'},
        ),
        migrations.AddField(
            model_name='hometype',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hometype',
            name='meta_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hometype',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
